version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_PASSWORD
        environment:
          DATABASE_HOSTNAME: localhost
          DATABASE_PORT: 5432
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: myappdb
          DATABASE_USERNAME: postgres
          TEST_DATABASE: myappdb

      - image: cimg/postgres:14.0
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_PASSWORD
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myappdb
          POSTGRES_USER: postgres

    steps:
      - checkout
      - run:
          name: Install pip packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and push to Dockerhub
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
            docker push $DOCKER_HUB_USER_ID/$IMAGE_NAME:latest    

        

workflows:
  version: 2
  build-master:
    jobs:
      - build
      - deploy:
          requires:
            - build
